spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect  # Dialect H2 cho Hibernate
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: laptrinhh2208@gmail.com
    password: bewq lkvf saii sasu
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true


